---

- name: test if postgres_port is set correctly
  assert:
    that:
      - postgres_port is defined
      - postgres_port is number
      - postgres_port > 0
      - postgres_port < 65536
    quiet: yes

- name: test if postgres_listen_addresses is set correctly
  assert:
    that:
      - postgres_listen_addresses is defined
      - postgres_listen_addresses is string
    quiet: yes

- name: test if postgres_unix_socket_directories is set correctly
  assert:
    that:
      - postgres_unix_socket_directories is defined
      - postgres_unix_socket_directories is string
    quiet: yes

- name: test if postgres_max_wal_size is set correctly
  assert:
    that:
      - postgres_max_wal_size is defined
      - postgres_max_wal_size is string
    quiet: yes

- name: test if postgres_min_wal_size is set correctly
  assert:
    that:
      - postgres_min_wal_size is defined
      - postgres_min_wal_size is string
    quiet: yes

- name: test if postgres_log_timezone is set correctly
  assert:
    that:
      - postgres_log_timezone is defined
      - postgres_log_timezone is string
      - postgres_log_timezone in postgres_acceptable_timezones
    quiet: yes

- name: test if postgres_datestyle is set correctly
  assert:
    that:
      - postgres_datestyle is defined
      - postgres_datestyle is string
    quiet: yes

- name: test if postgres_timezone is set correctly
  assert:
    that:
      - postgres_timezone is defined
      - postgres_timezone is string
      - postgres_timezone in postgres_acceptable_timezones
    quiet: yes

- name: test if postgres_default_text_search_config is set correctly
  assert:
    that:
      - postgres_default_text_search_config is defined
      - postgres_default_text_search_config is string
    quiet: yes

- name: test if postgres_hba_entries is set correctly
  assert:
    that:
      - postgres_hba_entries is defined
      - postgres_hba_entries is iterable
    quiet: yes

- name: test if postgres_databases is set correctly
  assert:
    that:
      - postgres_databases is iterable
    quiet: yes
  when:
    - postgres_databases is defined

- name: test if item.conn_limit in postgres_databases is set correctly
  assert:
    that:
      - item.conn_limit is number
      - item.conn_limit > 0
    quiet: yes
  loop: "{{ postgres_databases }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - postgres_databases is defined
    - item.conn_limit is defined

- name: test if item.trust_input in postgres_databases is set correctly
  assert:
    that:
      - item.trust_input is boolean
    quiet: yes
  loop: "{{ postgres_databases }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - postgres_databases is defined
    - item.trust_input is defined

- name: test if item.state in postgres_databases is set correctly
  assert:
    that:
      - item.state is string
      - item.state in [ "absent", "dump", "present", "restore" ]
    quiet: yes
  loop: "{{ postgres_databases }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - postgres_databases is defined
    - item.state is defined
