---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: postgres-fedora-latest
    image: fedora:latest
    pre_build_image: yes
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/usr/sbin/init"
    environment:
      container: docker
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: fedora-latest
