---
# handlers file for postgres
- name: restart postgres
  service:
    name: "{{ postgres_service }}"
    state: restarted

- name: reload postgres
  service:
    name: "{{ postgres_service }}"
    state: reloaded
