---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: ansible-role-postgres
      postgres_port: 6543
      postgres_databases:
        - name: test
      postgres_users:
        - name: test
          password: test
          db: test
