---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  tasks:
    - name: Remove postgres users
      community.postgresql.postgresql_user:
        name: test
        db: test
        port: 6543
        state: absent
      become_user: postgres
      become: true

    - name: Remove postgres database
      community.postgresql.postgresql_db:
        name: test
        port: 6543
        state: absent
      become: true
      become_user: postgres
