---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Remove postgres users
      community.postgresql.postgresql_user:
        name: test
        db: test
        port: 6543
        state: absent
      become_user: postgres
      become: yes

    - name: Remove postgres database
      community.postgresql.postgresql_db:
        name: test
        port: 6543
        state: absent
      become: yes
      become_user: postgres
